### ISSUE TITLE
Production Assets not loading

### ISSUE THREAD

**Issue by Talha5** [giannisp/rails-react-boilerplate#35]
When run in production environment, it doesnt load assets.

```
[0062043e-500e-4f46-8df1-8c718ce9b8aa] ActionView::Template::Error (no implicit conversion of nil into String):
[0062043e-500e-4f46-8df1-8c718ce9b8aa]     3:   <head>
[0062043e-500e-4f46-8df1-8c718ce9b8aa]     4:    <title>rails-react-boilerplate</title>
[0062043e-500e-4f46-8df1-8c718ce9b8aa]     5:     <%= csrf_meta_tags %>
[0062043e-500e-4f46-8df1-8c718ce9b8aa]     6:     <%= stylesheet_link_tag asset_path('app.css', 'css'), media: 'all' %>
[0062043e-500e-4f46-8df1-8c718ce9b8aa]     7:   </head>
[0062043e-500e-4f46-8df1-8c718ce9b8aa]     8: 
[0062043e-500e-4f46-8df1-8c718ce9b8aa]     9:   <body>
[0062043e-500e-4f46-8df1-8c718ce9b8aa]   
[0062043e-500e-4f46-8df1-8c718ce9b8aa] config/initializers/asset_loader.rb:21:in `+'
[0062043e-500e-4f46-8df1-8c718ce9b8aa] config/initializers/asset_loader.rb:21:in `get_asset_path'
[0062043e-500e-4f46-8df1-8c718ce9b8aa] app/helpers/application_helper.rb:3:in `asset_path'
[0062043e-500e-4f46-8df1-8c718ce9b8aa] app/views/layouts/application.html.erb:6

```

**Comment by giannisp** [comment]
Hello @Talha5, thanks for posting the issue.
I have updated the README file with more specific instructions:
https://github.com/giannisp/rails-react-boilerplate#run-in-production

So you just need to compile the assets first, and then run the rails server.
Using the default repo configuration assets should be served from publist/dist folder.
Let me know if this helps.
